In [1]:
import KLineForm as klf

In [2]:
klf.methodInfo.buy()

                           method        info type
0      is_bullish_candle_dominant     N周期阳线占优  buy
1            is_bullish_engulfing        看涨吞没  buy
2   is_bullish_engulfing_enhanced       阳包阴加强  buy
3       is_bullish_ma_arrangement      均线多头排列  buy
4                       is_gap_up        跳空上扬  buy
5             is_healthy_pullback    回调缩量上涨放量  buy
6            is_macd_golden_cross      MACD金叉  buy
7     is_macd_second_golden_cross  MACD零上二次金叉  buy
8                 is_morning_star        早晨之星  buy
9            is_moving_average_up        均线向上  buy
10     is_one_barrier_three_lines       一阳穿三线  buy
11                    is_piercing        曙光初现  buy
12         is_small_bullish_steps    底部连续小阳推升  buy
13        is_three_white_soldiers         红三兵  buy
14         is_two_crows_one_white         多方炮  buy
15           is_volume_price_sync   N周期量价同步走强  buy
16                ma_golden_cross        均线金叉  buy

In [3]:
klf.methodInfo.sell()

                                method             info  type
0             bears_dominant_in_n_days          N周期阴线占优  sell
1                descending_highs_lows      N周期高点低点逐步降低  sell
2       flat_open_low_close_big_volume   平开低走阴线 + 巨额成交量  sell
3     high_dark_cloud_with_bear_volume    高位乌云盖顶+中期阴量占优  sell
4       high_open_low_close_big_volume  高开低走大阴线 + 巨额成交量  sell
5        high_small_bears_distribution         高位连续小阴派发  sell
6       high_volume_stagnation_to_bear        高位放量滞涨转空头  sell
7                 is_bearish_engulfing             看跌吞没  sell
8                   is_bearish_soldier             空方尖兵  sell
9                  is_dark_cloud_cover             乌云盖顶  sell
10                is_evening_doji_star            黄昏十字星  sell
11                     is_evening_star              黄昏星  sell
12            is_falling_three_methods            下跌三部曲  sell
13           is_five_consecutive_bears            高档五连阴  sell
14                  is_gravestone_doji           高位墓碑十字  sell
15                      is_hanging_man            高位吊颈线  sell
16                       is_high_cross            高位十字星  sell
17                 is_macd_death_cross           MACD死叉  sell
18              is_moving_average_down             均线向下  sell
19            is_one_black_cross_three            一阴穿三线  sell
20                     is_pouring_rain             倾盆大雨  sell
21                is_three_black_crows             三只乌鸦  sell
22                        is_two_crows             双飞乌鸦  sell
23                  kdj_top_divergence           KDJ顶背离  sell
24        long_upper_shadow_big_volume     长上影线 + 巨额成交量  sell
25                      ma_death_cross             均线死叉  sell
26      macd_multiple_death_below_zero      MACD零轴下多次死叉  sell
27                 macd_top_divergence          MACD顶背离  sell
28       medium_term_volume_price_weak         中期量价同步走弱  sell
29  moving_average_bearish_arrangement           均线空头排列  sell
30             multiple_ma_death_cross        中长期均线死叉共振  sell
31                net_decline_dominant      N周期内跌幅远大于涨幅  sell
32         one_black_cross_multiple_ma        一阴穿多中长期均线  sell
33             rally_shrink_drop_swell         反弹缩量下跌放量  sell
34                  rsi_top_divergence           RSI顶背离  sell
35        volume_decline_bear_dominant     中长期量能递减但阴量占优  sell
36                   volume_stagnation             放量滞涨  sell